---
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-pfsense-controller
  namespace: kube-system
type: Opaque
data:
  # base64 encoded password
  # echo -n "mypassword" | base64
  pfsense-password:
